name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -o crestron-discover

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: crestron-discover

      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v2
        with:
          formula-name: crestron-discover
          homebrew-tap: mikejobson/homebrew-tap
          download-url: https://github.com/mikejobson/crestron-discover/releases/download/${{ github.ref_name }}/crestron-discover
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
